### ISSUE TITLE
Crash of EWBF watchdog

### ISSUE THREAD

**Issue by zimpixa** [Undertrey/ZcashMinerAutorun#16]
EWBF bug report
If those messages are detected in log watchbot crashes
`20.07.2018 08:19:21 CUDA: Device: 0 Thread exited with message: "all CUDA-capable devices are busy or unavailable"
02.08.2018 15:33:25 CUDA: Device: 1 Thread exited with message: "an illegal memory access was encountered"`

Error written in watchbot log

` [2018-08-02][15:36:27] CUDA-capable`

It happens on every detected line that contains "

`>> %~n0.log ECHO [%Date%][%Time:~-11,8%] reports:%reports% 3:%~3 Chat:%chatid%
prints
reports:0 3:02.08.2018 15:33:25 CUDA: Device: 1 Thread exited with message: "an Chat:0
`

When I added REM to lines 796 and 797 watchbot works fine
I've tried to edit those lines, to just write to log simple message, but it also didn't work

Also I see this version is still missing current server and queue number

**Comment by Undertrey** [comment]
Hello. Thank you for reporting. Fixed in latest version.
About current server and queue number please do not miss an order of commands in config.ini file - first must be an "-server"

miner.exe --server eu1-zcash.flypool.org --algo 192_7 --port 3333 --user t1S8HRoMoyhBhwXq6zY5vHwqhd9MHSiHWKv.acrefawn --pass x --log 2 --fee 0 --templimit 80 --pec
